/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniil Shmelev
-/
import BSeries.LieButcher.Algebra

/-!
# Commutator-Free Lie Group Methods

This file defines the algebraic skeleton of commutator-free Lie group methods.
Such methods advance by composing exponentials of linear combinations of stage
generators, avoiding explicit commutators in the method format.

## Main definitions

* `StageCombination` - coefficients of a linear combination of stage generators
* `ExponentialAction` - an abstract exponential action on a state space
* `CommutatorFreeMethod` - stage and step exponential coefficient lists
* `CommutatorFreeMethod.stagePoint` - stage point from precomputed generators
* `CommutatorFreeMethod.step` - one commutator-free step from precomputed generators

## References

* Celledoni, Marthinsen, Owren, *Commutator-free Lie group methods*
* Owren, *Order conditions for commutator-free Lie group methods*
-/

namespace BSeries

open HopfAlgebras

open scoped BigOperators

universe u v w x

noncomputable section

/-- Coefficients of a linear combination of stage generators. -/
abbrev StageCombination (ι : Type u) (R : Type v) : Type (max u v) :=
  ι → R

namespace StageCombination

variable {ι : Type u} {R : Type v} {E : Type w}

/-- Evaluate a stage linear combination on stage generator data. -/
def eval [Fintype ι] [Semiring R] [AddCommMonoid E] [Module R E]
    (c : StageCombination ι R) (K : ι → E) : E :=
  ∑ i, c i • K i

theorem eval_congr [Fintype ι] [Semiring R] [AddCommMonoid E] [Module R E]
    {c d : StageCombination ι R} {K L : ι → E}
    (hc : ∀ i, c i = d i) (hK : ∀ i, K i = L i) :
    eval c K = eval d L := by
  unfold eval
  apply Finset.sum_congr rfl
  intro i _
  rw [hc i, hK i]

theorem eval_congr_coeff [Fintype ι] [Semiring R] [AddCommMonoid E] [Module R E]
    {c d : StageCombination ι R} (K : ι → E)
    (hc : ∀ i, c i = d i) :
    eval c K = eval d K :=
  eval_congr hc fun _ => rfl

theorem eval_congr_data [Fintype ι] [Semiring R] [AddCommMonoid E] [Module R E]
    (c : StageCombination ι R) {K L : ι → E}
    (hK : ∀ i, K i = L i) :
    eval c K = eval c L :=
  eval_congr (fun _ => rfl) hK

@[simp]
theorem eval_zero_coeff [Fintype ι] [Semiring R] [AddCommMonoid E] [Module R E]
    (K : ι → E) :
    eval (fun _ : ι => (0 : R)) K = 0 := by
  simp [eval]

@[simp]
theorem eval_zero_data [Fintype ι] [Semiring R] [AddCommMonoid E] [Module R E]
    (c : StageCombination ι R) :
    eval c (fun _ : ι => (0 : E)) = 0 := by
  simp [eval]

@[simp]
theorem eval_punit [Semiring R] [AddCommMonoid E] [Module R E]
    (c : StageCombination PUnit R) (K : PUnit → E) :
    eval c K = c PUnit.unit • K PUnit.unit := by
  simp [eval]

end StageCombination

/-- An abstract exponential action generated by elements of `A`. -/
structure ExponentialAction (A : Type u) (M : Type v) [Zero A] where
  act : A → M → M
  act_zero : ∀ y, act 0 y = y

namespace ExponentialAction

variable {A : Type u} {M : Type v} [Zero A]

/-- Compose exponentials in list order. -/
def applyList (Φ : ExponentialAction A M) : List A → M → M
  | [], y => y
  | a :: as, y => applyList Φ as (Φ.act a y)

@[simp]
theorem applyList_nil (Φ : ExponentialAction A M) (y : M) :
    Φ.applyList [] y = y :=
  rfl

@[simp]
theorem applyList_cons (Φ : ExponentialAction A M) (a : A) (as : List A) (y : M) :
    Φ.applyList (a :: as) y = Φ.applyList as (Φ.act a y) :=
  rfl

@[simp]
theorem applyList_singleton (Φ : ExponentialAction A M) (a : A) (y : M) :
    Φ.applyList [a] y = Φ.act a y :=
  rfl

theorem applyList_congr {Φ : ExponentialAction A M} :
    ∀ {as bs : List A}, as = bs → ∀ y, Φ.applyList as y = Φ.applyList bs y
  | _, _, rfl, _ => rfl

@[simp]
theorem applyList_zero_singleton (Φ : ExponentialAction A M) (y : M) :
    Φ.applyList [0] y = y := by
  simp [Φ.act_zero]

end ExponentialAction

/-- A commutator-free method represented by lists of stage-generator combinations. -/
structure CommutatorFreeMethod (ι : Type u) (R : Type v) where
  stageExps : ι → List (StageCombination ι R)
  stepExps : List (StageCombination ι R)

namespace CommutatorFreeMethod

variable {ι : Type u} {R : Type v} {A : Type w} {M : Type x}

/-- The method with no exponential evaluations. -/
def identity (ι : Type u) (R : Type v) : CommutatorFreeMethod ι R where
  stageExps _ := []
  stepExps := []

/-- A one-stage, one-exponential method with coefficient `1`. -/
def singleExponential (R : Type v) [One R] : CommutatorFreeMethod PUnit R where
  stageExps _ := []
  stepExps := [fun _ => 1]

/-- Stage generators produced by evaluating the stage exponential combinations. -/
def stageGenerators [Fintype ι] [Semiring R] [AddCommMonoid A] [Module R A]
    (cf : CommutatorFreeMethod ι R) (K : ι → A) (i : ι) : List A :=
  (cf.stageExps i).map fun c => StageCombination.eval c K

/-- Step generators produced by evaluating the output exponential combinations. -/
def stepGenerators [Fintype ι] [Semiring R] [AddCommMonoid A] [Module R A]
    (cf : CommutatorFreeMethod ι R) (K : ι → A) : List A :=
  cf.stepExps.map fun c => StageCombination.eval c K

/-- A stage point obtained by composing the stage exponentials. -/
def stagePoint [Fintype ι] [Semiring R] [AddCommMonoid A] [Module R A]
    (cf : CommutatorFreeMethod ι R) (Φ : ExponentialAction A M)
    (K : ι → A) (i : ι) (y : M) : M :=
  Φ.applyList (cf.stageGenerators K i) y

/-- One commutator-free step from precomputed stage generators. -/
def step [Fintype ι] [Semiring R] [AddCommMonoid A] [Module R A]
    (cf : CommutatorFreeMethod ι R) (Φ : ExponentialAction A M)
    (K : ι → A) (y : M) : M :=
  Φ.applyList (cf.stepGenerators K) y

@[simp]
theorem identity_stageGenerators [Fintype ι] [Semiring R]
    [AddCommMonoid A] [Module R A] (K : ι → A) (i : ι) :
    (identity ι R).stageGenerators K i = [] :=
  rfl

@[simp]
theorem identity_stepGenerators [Fintype ι] [Semiring R]
    [AddCommMonoid A] [Module R A] (K : ι → A) :
    (identity ι R).stepGenerators K = [] :=
  rfl

@[simp]
theorem identity_stagePoint [Fintype ι] [Semiring R]
    [AddCommMonoid A] [Module R A]
    (Φ : ExponentialAction A M) (K : ι → A) (i : ι) (y : M) :
    (identity ι R).stagePoint Φ K i y = y :=
  rfl

@[simp]
theorem identity_step [Fintype ι] [Semiring R]
    [AddCommMonoid A] [Module R A]
    (Φ : ExponentialAction A M) (K : ι → A) (y : M) :
    (identity ι R).step Φ K y = y :=
  rfl

theorem stageGenerators_congr_data [Fintype ι] [Semiring R]
    [AddCommMonoid A] [Module R A]
    (cf : CommutatorFreeMethod ι R) {K L : ι → A}
    (hK : ∀ i, K i = L i) (i : ι) :
    cf.stageGenerators K i = cf.stageGenerators L i := by
  unfold stageGenerators
  apply List.map_congr_left
  intro c _
  exact StageCombination.eval_congr_data c hK

theorem stepGenerators_congr_data [Fintype ι] [Semiring R]
    [AddCommMonoid A] [Module R A]
    (cf : CommutatorFreeMethod ι R) {K L : ι → A}
    (hK : ∀ i, K i = L i) :
    cf.stepGenerators K = cf.stepGenerators L := by
  unfold stepGenerators
  apply List.map_congr_left
  intro c _
  exact StageCombination.eval_congr_data c hK

theorem stagePoint_congr_data [Fintype ι] [Semiring R]
    [AddCommMonoid A] [Module R A]
    (cf : CommutatorFreeMethod ι R) (Φ : ExponentialAction A M)
    {K L : ι → A} (hK : ∀ i, K i = L i) (i : ι) (y : M) :
    cf.stagePoint Φ K i y = cf.stagePoint Φ L i y := by
  rw [stagePoint, stagePoint, cf.stageGenerators_congr_data hK i]

theorem step_congr_data [Fintype ι] [Semiring R]
    [AddCommMonoid A] [Module R A]
    (cf : CommutatorFreeMethod ι R) (Φ : ExponentialAction A M)
    {K L : ι → A} (hK : ∀ i, K i = L i) (y : M) :
    cf.step Φ K y = cf.step Φ L y := by
  rw [step, step, cf.stepGenerators_congr_data hK]

@[simp]
theorem singleExponential_stageGenerators [Semiring R] [AddCommMonoid A] [Module R A]
    (K : PUnit → A) (i : PUnit) :
    (singleExponential R).stageGenerators K i = [] :=
  rfl

@[simp]
theorem singleExponential_stepGenerators [Semiring R] [AddCommMonoid A] [Module R A]
    (K : PUnit → A) :
    (singleExponential R).stepGenerators K = [K PUnit.unit] := by
  ext x
  simp [stepGenerators, singleExponential]

@[simp]
theorem singleExponential_stagePoint [Semiring R]
    [AddCommMonoid A] [Module R A]
    (Φ : ExponentialAction A M) (K : PUnit → A) (i : PUnit) (y : M) :
    (singleExponential R).stagePoint Φ K i y = y :=
  rfl

@[simp]
theorem singleExponential_step [Semiring R]
    [AddCommMonoid A] [Module R A]
    (Φ : ExponentialAction A M) (K : PUnit → A) (y : M) :
    (singleExponential R).step Φ K y = Φ.act (K PUnit.unit) y := by
  simp [step]

end CommutatorFreeMethod

end

end BSeries
